kind: ServiceMeshControlPlane
apiVersion: maistra.io/v2
metadata:
  name: basic
  namespace: istio-system
spec:
  security:
    certificateAuthority:
      cert-manager:
        address: cert-manager-istio-csr.cert-manager.svc:443
#        pilotSecretName: istiod-tls  #Should this be "istio-ca" to match the other examples?
        pilotSecretName: istio-ca 
        rootCAConfigMapName: "istio-ca-root-cert"
      type: cert-manager
  gateways:
    openshiftRoute:
      enabled: false
  version: v2.3
  tracing:
    type: Jaeger
    sampling: 10000
  policy:
    type: Istiod
  telemetry:
    type: Istiod
  proxy:
    logging:
      level: debug
  addons:
    jaeger:
      install:
        storage:
          type: Memory
    prometheus:
      enabled: true
    kiali:
      enabled: true
    grafana:
      enabled: true
