kind: ServiceMeshControlPlane
apiVersion: maistra.io/v2
metadata:
  name: basic
  namespace: istio-system
spec:
  gateways:
    openshiftRoute:
      enabled: true  # This is needed since this demo still relies on auto-routes!
# See: https://docs.openshift.com/container-platform/4.16/service_mesh/v2x/servicemesh-release-notes.html#istio-openshift-routing-ior-default-setting-change
  version: v2.6
  tracing:
    type: Jaeger
    sampling: 10000
  policy:
    type: Istiod
  telemetry:
    type: Istiod
  proxy:
    logging:
      level: debug
  addons:
    jaeger:
      install:
        storage:
          type: Memory
    prometheus:
      enabled: true
    kiali:
      enabled: true
    grafana:
      enabled: true
