apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: sailoperator.io/v1alpha1
kind: Istio
metadata:
  name: default
spec:
  namespace: istio-system
  updateStrategy:
    type: InPlace
    inactiveRevisionDeletionGracePeriodSeconds: 30
  version: v1.23.0
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-cni
---
kind: IstioCNI
apiVersion: sailoperator.io/v1alpha1
metadata:
  name: default
spec:
  namespace: istio-cni
  version: v1.23.0
