apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    kiali_wizard: request_routing
  name: travels
  namespace: travel-agency
spec:
  hosts:
  - travels.travel-agency.svc.cluster.local
  http:
  - route:
    - destination:
        host: travels.travel-agency.svc.cluster.local
        subset: v1
      weight: 90
    - destination:
        host: travels.travel-agency.svc.cluster.local
        subset: v2
      weight: 10
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  labels:
    kiali_wizard: request_routing
  name: travels
  namespace: travel-agency
spec:
  host: travels.travel-agency.svc.cluster.local
  subsets:
  - labels:
      version: v1
    name: v1
  - labels:
      version: v2
    name: v2
