apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    kiali_wizard: request_routing
  name: travels
  namespace: travel-agency
spec:
  hosts:
  - travels.travel-agency.svc.cluster.local
  http:
  - match:
    - headers:
        portal:
          exact: viaggi.it
    route:
    - destination:
        host: travels.travel-agency.svc.cluster.local
        subset: v1
      weight: 0
    - destination:
        host: travels.travel-agency.svc.cluster.local
        subset: v2
      weight: 100
    - destination:
        host: travels.travel-agency.svc.cluster.local
        subset: v3
      weight: 0
  - match:
    - headers:
        portal:
          exact: travels.uk
    route:
    - destination:
        host: travels.travel-agency.svc.cluster.local
        subset: v1
      weight: 0
    - destination:
        host: travels.travel-agency.svc.cluster.local
        subset: v2
      weight: 0
    - destination:
        host: travels.travel-agency.svc.cluster.local
        subset: v3
      weight: 100
  - route:
    - destination:
        host: travels.travel-agency.svc.cluster.local
        subset: v1
      weight: 100
    - destination:
        host: travels.travel-agency.svc.cluster.local
        subset: v2
      weight: 0
    - destination:
        host: travels.travel-agency.svc.cluster.local
        subset: v3
      weight: 0
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  labels:
    kiali_wizard: request_routing
  name: travels
  namespace: travel-agency
spec:
  host: travels.travel-agency.svc.cluster.local
  subsets:
  - labels:
      version: v1
    name: v1
  - labels:
      version: v2
    name: v2
  - labels:
      version: v3
    name: v3
